### ISSUE TITLE
Error: Filename too long:

### ISSUE THREAD

**Issue by JJ** [raiben/tropescraper#21]
```
INFO:tropescraper.adaptors.file_cache:Cache set for https://www.google.com/url?client=internal-element-cse&cx=006443654034974345143:kc4pt9dnkle&q=https://tvtropes.org/pmwiki/pmwiki.php/Main/Stripperiffic&sa=U&ved=2ahUKEwiP9Y6Bn-TuAhUPxBQKHfzSCaAQFjAAegQIBRAB&usg=AOvVaw08ye5O--r01JSLSALpnkRc
Traceback (most recent call last):
  File "/home/jmerelo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tropescraper/use_cases/scrape_tropes_use_case.py", line 209, in extract_all_tropes_in_page_recursively
    self.extract_all_tropes_in_page_recursively(page, subtrope, recursivity_level)
  File "/home/jmerelo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tropescraper/use_cases/scrape_tropes_use_case.py", line 209, in extract_all_tropes_in_page_recursively
    self.extract_all_tropes_in_page_recursively(page, subtrope, recursivity_level)
  File "/home/jmerelo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tropescraper/use_cases/scrape_tropes_use_case.py", line 209, in extract_all_tropes_in_page_recursively
    self.extract_all_tropes_in_page_recursively(page, subtrope, recursivity_level)
  [Previous line repeated 993 more times]
  File "/home/jmerelo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tropescraper/use_cases/scrape_tropes_use_case.py", line 207, in extract_all_tropes_in_page_recursively
    page = self._retrieve(full_link)
  File "/home/jmerelo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tropescraper/use_cases/scrape_tropes_use_case.py", line 131, in _retrieve
    self._cache.set(url, content)
  File "/home/jmerelo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tropescraper/adaptors/file_cache.py", line 58, in set
    self._write_file(file_path, encoded_content)
  File "/home/jmerelo/.pyenv/versions/3.9.0/lib/python3.9/site-packages/tropescraper/adaptors/file_cache.py", line 64, in _write_file
    with open(compressed_path, 'wb') as file:
OSError: [Errno 36] File name too long: './scraper_cache/aHR0cHM6Ly93d3cuZ29vZ2xlLmNvbS91cmw_Y2xpZW50PWludGVybmFsLWVsZW1lbnQtY3NlJmN4PTAwNjQ0MzY1NDAzNDk3NDM0NTE0MzprYzRwdDlkbmtsZSZxPWh0dHBzOi8vdHZ0cm9wZXMub3JnL3Btd2lraS9wbXdpa2kucGhwL01haW4vU3RyaXBwZXJpZmZpYyZzYT1VJnZlZD0yYWhVS0V3aVA5WTZCbi1UdUFoVVB4QlFLSGZ6U0NhQVFGakFBZWdRSUJSQUImdXNnPUFPdlZhdzA4eWU1Ty0tcjAxSlNMU0FMcG5rUmM=.html.bz2'
```

Can't find out where it failed. Will check it out.

**Comment by JJ** [comment]
The problem is that it's following urls such as this one: 
```
INFO:tropescraper.adaptors.file_cache:Cache miss for https://www.google.com/url?client=internal-element-cse&cx=006443654034974345143:kc4pt9dnkle&q=https://tvtropes.org/pmwiki/pmwiki.php/Main/Stripperiffic&sa=U&ved=2ahUKEwiP9Y6Bn-TuAhUPxBQKHfzSCaAQFjAAegQIBRAB&usg=AOvVaw08ye5O--r01JSLSALpnkRc
```
